remove the images if any + some railguards
some aditional error checking
ensure that images are removed when saving /boot to not blow up the memory (/run is on a tmpfs)

diff --git a/templates/raspbian/resources/usr/share/initramfs-tools/scripts/cattlepi-base/helpers b/templates/raspbian/resources/usr/share/initramfs-tools/scripts/cattlepi-base/helpers
--- a/templates/raspbian/resources/usr/share/initramfs-tools/scripts/cattlepi-base/helpers
+++ b/templates/raspbian/resources/usr/share/initramfs-tools/scripts/cattlepi-base/helpers
@@ -136,11 +136,25 @@ cattlepi_fetch_update_config()
 cattlepi_check_apply_disk_layout()
 {
     cattlepi_fetch_update_config
+    if [ -r /boot/sdlayout.json" ]; then
+        # we only allow one manipulation of the sdlayout.
+        # after that you need to explicitely remove /boot/sdlayout.json to alter the layout again
+        echo "an sdlayout was already applied. will skip this"
+        echo "remove /boot/sdlayout.json if you want to apply another layout"
+        return
+    fi
     jq -r ".config.sdlayout" "${CATTLEPI_DIR}/config" | grep -q null
     if [ $? -ne 0 ]; then
         # pull down and decode the requested disk layout
         jq -r ".config.sdlayout" "${CATTLEPI_DIR}/config" | base64 -d > /tmp/sdlayout
-        # TODO: there should be proper error checking here, but do the bare minimum here
+        if [ $? -ne 0 ]; then
+            echo "invalid sdlayout. skipping"
+            return
+        fi
+        if [ -z "$(cat /tmp/sdlayout)" ]; then
+            echo "configuration is empty. skipping";
+            return
+        fi
         # dump current config
         sfdisk -d /dev/mmcblk0 | grep -v label-id: > /tmp/current_sdlayout
         cmp -s /tmp/sdlayout /tmp/current_sdlayout
@@ -148,9 +162,8 @@ cattlepi_check_apply_disk_layout()
             # we need to apply the requested layout
             #   to keep things "bootable" we will backup the content under /boot, apply the layout
             #   and afterwards copy back the backup to the boot partition
+            rm -rf "${CATTLEPI_IMAGES_DIR}"
             mkdir /run/bootbk
-            # TODO: here we will need to remove all the images to prevent copying (and filling the memory as the
-            # /run in on a tmpfs, therefore in memory)
             cp -R /boot/* /run/bootbk
             umount /boot
             # showtime: apply the requested layout
